###
GET http://localhost:8080/locations/3
Accept: application/json


###
POST http://localhost:8080/locations
Content-Type: application/json
Accept: application/json

{
  "name": "Dunaharaszti",
  "lat": 47.34,
  "lon": 19.08
}

###
PUT http://localhost:8080/locations/3
Content-Type: application/json
Accept: application/json

{
  "name": "Dunaharaszti",
  "lat": 97.34,
  "lon": 19.08
}

###
DELETE http://localhost:8080/locations/3
