###
GET http://localhost:8080/api/instruments
Accept: application/json

###
GET http://localhost:8080/api/instruments?price=95000
Accept: application/json

###
POST http://localhost:8080/api/instruments
Content-Type: application/json
Accept: application/json

{
  "brand": "",
  "instrumentType": "ELECTRIC_GUITAR",
  "price": -75000
}

###
PUT http://localhost:8080/api/instruments/2
Content-Type: application/json
Accept: application/json

{
"price": 170000
}

###
DELETE http://localhost:8080/api/instruments/3

###
DELETE http://localhost:8080/api/instruments

###
GET http://localhost:8080/api/instruments/7
Accept: application/json