POST http://localhost:8080/api/authors
Content-Type: application/json
Accept: application/json

{
  "name": "Tolkien"
}

###
GET http://localhost:8080/api/authors
Accept: application/json

###
POST http://localhost:8080/api/authors/1
Content-Type: application/json
Accept: application/json

{
  "numberISBN": "123456",
  "title": "Hobbit"
}

###
POST http://localhost:8080/api/authors/1
Content-Type: application/json
Accept: application/json

{
  "numberISBN": "123457",
  "title": "LOTR"
}

###
DELETE http://localhost:8080/api/authors/1
